namespace Bimss.Domain.Membership;

// Immutable metadata record — the underlying file bytes live in
// IMemberDocumentStorage (Bimss.Application/Membership), never in the
// database. If a document is wrong, upload a corrected one; the old
// metadata row stays for audit trail, per AGENTS.md's rule against
// overwriting auditable records. No update method by design.
public sealed class MemberDocument
{
    // Accepted file types are PDF, JPG, and PNG (confirmed with Buklod,
    // 2026-08-14; feeds member verification, which requires proof of
    // employment before it can proceed).
    private static readonly HashSet<string> AcceptedContentTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        "application/pdf",
        "image/jpeg",
        "image/png",
    };

    public MemberDocument(
        Guid id,
        Guid memberId,
        string documentType,
        string originalFileName,
        string contentType,
        string storageKey,
        long fileSizeBytes,
        DateTimeOffset uploadedAtUtc,
        Guid? uploadedByUserId)
    {
        if (memberId == Guid.Empty)
        {
            throw new ArgumentException("Member is required.", nameof(memberId));
        }

        ArgumentException.ThrowIfNullOrWhiteSpace(documentType);
        ArgumentException.ThrowIfNullOrWhiteSpace(originalFileName);
        ArgumentException.ThrowIfNullOrWhiteSpace(contentType);
        ArgumentException.ThrowIfNullOrWhiteSpace(storageKey);

        if (!AcceptedContentTypes.Contains(contentType))
        {
            throw new ArgumentException($"Content type '{contentType}' is not an accepted document type.", nameof(contentType));
        }

        ArgumentOutOfRangeException.ThrowIfLessThanOrEqual(fileSizeBytes, 0);

        Id = id;
        MemberId = memberId;
        DocumentType = documentType;
        OriginalFileName = originalFileName;
        ContentType = contentType;
        StorageKey = storageKey;
        FileSizeBytes = fileSizeBytes;
        UploadedAtUtc = uploadedAtUtc;
        UploadedByUserId = uploadedByUserId;
    }

    public Guid Id { get; private set; }

    public Guid MemberId { get; private set; }

    public string DocumentType { get; private set; } = string.Empty;

    // Display only — never used to derive a storage path (see
    // docs/SECURITY_AND_PRIVACY.md's "do not trust original file paths").
    public string OriginalFileName { get; private set; } = string.Empty;

    public string ContentType { get; private set; } = string.Empty;

    // Server-generated by IMemberDocumentStorage; opaque, never derived from
    // OriginalFileName.
    public string StorageKey { get; private set; } = string.Empty;

    public long FileSizeBytes { get; private set; }

    public DateTimeOffset UploadedAtUtc { get; private set; }

    public Guid? UploadedByUserId { get; private set; }
}
