<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bimss.Application\Bimss.Application.csproj" />
    <ProjectReference Include="..\Bimss.Infrastructure\Bimss.Infrastructure.csproj" />
    <ProjectReference Include="..\Bimss.Contracts\Bimss.Contracts.csproj" />
  </ItemGroup>

</Project>
